// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceChangeStats {
    #[prost(message, optional, tag="1")]
    pub current: ::core::option::Option<BalanceChangeStat>,
    #[prost(message, optional, tag="2")]
    pub total: ::core::option::Option<BalanceChangeStat>,
    /// block
    #[prost(uint64, tag="99")]
    pub block_number: u64,
    #[prost(message, optional, tag="100")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceChangeStat {
    #[prost(uint64, tag="1")]
    pub type1_balance_changes: u64,
    #[prost(uint64, tag="2")]
    pub type2_balance_changes: u64,
    #[prost(uint64, tag="3")]
    pub balance_changes: u64,
    #[prost(uint64, tag="4")]
    pub transfers: u64,
    #[prost(uint64, tag="5")]
    pub transfers_not_matched: u64,
    #[prost(string, tag="6")]
    pub valid_rate: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
