// @generated
// This file is @generated by prost-build.
/// ERC1155 Metadata
/// <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol>
/// <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/extensions/ERC1155Supply.sol>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub metadata_by_contracts: ::prost::alloc::vec::Vec<MetadataByContract>,
    #[prost(message, repeated, tag="2")]
    pub metadata_by_tokens: ::prost::alloc::vec::Vec<MetadataByToken>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataByContract {
    /// log.address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// symbol() -> string
    #[prost(string, optional, tag="2")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    /// name() -> string
    #[prost(string, optional, tag="3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataByToken {
    /// log.address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    /// uri(uint256 id) -> string
    #[prost(string, tag="3")]
    pub uri: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
