// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    /// RPC Poller
    #[prost(message, repeated, tag="1")]
    pub transfers: ::prost::alloc::vec::Vec<Transfer>,
    #[prost(message, repeated, tag="2")]
    pub transfers_from_fees: ::prost::alloc::vec::Vec<Transfer>,
    /// EXTENDED ONLY
    #[prost(message, repeated, tag="3")]
    pub extended_transfers_from_calls: ::prost::alloc::vec::Vec<Transfer>,
    #[prost(message, repeated, tag="4")]
    pub extended_transfers_from_block_rewards: ::prost::alloc::vec::Vec<Transfer>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    /// -- transaction --
    ///
    /// block rewards don't have tx_hash
    #[prost(bytes="vec", optional, tag="1")]
    pub tx_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// -- event --
    #[prost(bytes="vec", tag="10")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="11")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="12")]
    pub value: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
