// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Algorithm {
    Unspecified = 0,
    /// log event
    Log = 1,
    /// call
    Call = 2,
    /// child calls
    ChildCalls = 3,
    /// which the balances grow over time due to accrued interest
    RebasingToken = 4,
    /// RPC call
    Rpc = 5,
    /// RPC call missing
    RpcFail = 6,
    /// block balance changes
    Block = 10,
    /// failed transaction
    Failed = 11,
    /// gas fee consumed
    Gas = 12,
    /// from transaction
    Transaction = 13,
    /// from transaction fee
    TransactionFee = 14,
    /// from transaction fee burned EIP-1559
    TransactionFeeBurn = 15,
    /// from transaction fee tip EIP-1559
    TransactionFeePriorityFee = 16,
    /// system contract
    System = 20,
}
impl Algorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Algorithm::Unspecified => "ALGORITHM_UNSPECIFIED",
            Algorithm::Log => "ALGORITHM_LOG",
            Algorithm::Call => "ALGORITHM_CALL",
            Algorithm::ChildCalls => "ALGORITHM_CHILD_CALLS",
            Algorithm::RebasingToken => "ALGORITHM_REBASING_TOKEN",
            Algorithm::Rpc => "ALGORITHM_RPC",
            Algorithm::RpcFail => "ALGORITHM_RPC_FAIL",
            Algorithm::Block => "ALGORITHM_BLOCK",
            Algorithm::Failed => "ALGORITHM_FAILED",
            Algorithm::Gas => "ALGORITHM_GAS",
            Algorithm::Transaction => "ALGORITHM_TRANSACTION",
            Algorithm::TransactionFee => "ALGORITHM_TRANSACTION_FEE",
            Algorithm::TransactionFeeBurn => "ALGORITHM_TRANSACTION_FEE_BURN",
            Algorithm::TransactionFeePriorityFee => "ALGORITHM_TRANSACTION_FEE_PRIORITY_FEE",
            Algorithm::System => "ALGORITHM_SYSTEM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALGORITHM_UNSPECIFIED" => Some(Self::Unspecified),
            "ALGORITHM_LOG" => Some(Self::Log),
            "ALGORITHM_CALL" => Some(Self::Call),
            "ALGORITHM_CHILD_CALLS" => Some(Self::ChildCalls),
            "ALGORITHM_REBASING_TOKEN" => Some(Self::RebasingToken),
            "ALGORITHM_RPC" => Some(Self::Rpc),
            "ALGORITHM_RPC_FAIL" => Some(Self::RpcFail),
            "ALGORITHM_BLOCK" => Some(Self::Block),
            "ALGORITHM_FAILED" => Some(Self::Failed),
            "ALGORITHM_GAS" => Some(Self::Gas),
            "ALGORITHM_TRANSACTION" => Some(Self::Transaction),
            "ALGORITHM_TRANSACTION_FEE" => Some(Self::TransactionFee),
            "ALGORITHM_TRANSACTION_FEE_BURN" => Some(Self::TransactionFeeBurn),
            "ALGORITHM_TRANSACTION_FEE_PRIORITY_FEE" => Some(Self::TransactionFeePriorityFee),
            "ALGORITHM_SYSTEM" => Some(Self::System),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
