// @generated
// This file is @generated by prost-build.
/// ERC721 Metadata
/// <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/IERC721Metadata.sol>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub metadata_by_contracts: ::prost::alloc::vec::Vec<MetadataByContract>,
    #[prost(message, repeated, tag="2")]
    pub metadata_by_tokens: ::prost::alloc::vec::Vec<MetadataByToken>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataByContract {
    /// log.address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// 0x95d89b41: symbol() -> string
    #[prost(string, optional, tag="4")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    /// 0x61a4422b: name() -> string
    #[prost(string, optional, tag="5")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// 0x6c0360eb: baseURI() -> string
    #[prost(string, optional, tag="6")]
    pub base_uri: ::core::option::Option<::prost::alloc::string::String>,
    /// 0x18160ddd: totalSupply() -> uint256
    #[prost(string, optional, tag="7")]
    pub total_supply: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataByToken {
    /// log.address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    /// 0xc87b56dd: tokenURI(uint256 tokenId) -> string
    #[prost(string, optional, tag="3")]
    pub uri: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
