// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    /// RPC Poller
    #[prost(message, repeated, tag="1")]
    pub balances_by_account: ::prost::alloc::vec::Vec<BalanceByAccount>,
    /// EXTENDED ONLY
    #[prost(message, repeated, tag="2")]
    pub extended_balances_by_account_from_block_rewards: ::prost::alloc::vec::Vec<BalanceByAccount>,
    #[prost(message, repeated, tag="3")]
    pub extended_balances_by_account_from_calls: ::prost::alloc::vec::Vec<BalanceByAccount>,
    #[prost(message, repeated, tag="4")]
    pub extended_balances_by_account_from_system_calls: ::prost::alloc::vec::Vec<BalanceByAccount>,
    #[prost(message, repeated, tag="5")]
    pub extended_balances_by_account_from_gas: ::prost::alloc::vec::Vec<BalanceByAccount>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BalanceByAccount {
    /// -- transaction --
    ///
    /// block rewards & system calls don't have tx_hash
    #[prost(bytes="vec", optional, tag="1")]
    pub tx_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="2")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    /// eth_getBalance(address account) -> uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
