// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub contracts: ::prost::alloc::vec::Vec<Contract>,
    #[prost(message, repeated, tag="2")]
    pub contract_creations: ::prost::alloc::vec::Vec<ContractCreation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contract {
    /// -- contract --
    #[prost(bytes="vec", tag="20")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="21")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="22")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(int32, tag="23")]
    pub decimals: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractCreation {
    /// -- transaction --
    #[prost(bytes="vec", tag="5")]
    pub transaction_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// -- contract --
    #[prost(bytes="vec", tag="20")]
    pub address: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
