// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub contract_creations: ::prost::alloc::vec::Vec<ContractCreation>,
    #[prost(message, repeated, tag="2")]
    pub contract_changes: ::prost::alloc::vec::Vec<ContractChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractCreation {
    /// -- transaction --
    #[prost(bytes="vec", tag="5")]
    pub transaction_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// -- call --
    ///
    /// call.caller
    #[prost(bytes="vec", tag="8")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// -- ordering --
    ///
    /// code_change.ordinal
    #[prost(uint64, tag="10")]
    pub ordinal: u64,
    /// -- contract --
    ///
    /// code_change.address
    #[prost(bytes="vec", tag="20")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// code_change.new_hash
    #[prost(bytes="vec", tag="21")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractChange {
    /// -- transaction --
    #[prost(bytes="vec", optional, tag="5")]
    pub transaction_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// -- call --
    #[prost(bytes="vec", optional, tag="8")]
    pub caller: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// -- ordering --
    ///
    /// log.ordinal
    #[prost(uint64, optional, tag="10")]
    pub ordinal: ::core::option::Option<u64>,
    /// -- contract --
    #[prost(bytes="vec", tag="20")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="21")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="22")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="23")]
    pub decimals: ::core::option::Option<i32>,
}
// @@protoc_insertion_point(module)
