// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub contract_changes: ::prost::alloc::vec::Vec<ContractChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractChange {
    /// -- transaction --
    #[prost(bytes="vec", optional, tag="5")]
    pub transaction_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// -- ordering --
    ///
    /// log.ordinal
    #[prost(uint64, optional, tag="10")]
    pub ordinal: ::core::option::Option<u64>,
    /// relative index
    #[prost(uint64, tag="11")]
    pub index: u64,
    /// latest global sequence (block_num << 32 + index)
    #[prost(uint64, tag="12")]
    pub global_sequence: u64,
    /// -- contract --
    #[prost(bytes="vec", tag="20")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag="21")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="22")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="23")]
    pub decimals: ::core::option::Option<i32>,
}
// @@protoc_insertion_point(module)
