// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub tokens: ::prost::alloc::vec::Vec<Token>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token {
    /// log.address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    /// ERC721 Metadata
    /// <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/IERC721Metadata.sol>
    ///
    /// tokenURI(uint256 tokenId) -> string
    #[prost(string, optional, tag="3")]
    pub uri: ::core::option::Option<::prost::alloc::string::String>,
    /// symbol() -> string
    #[prost(string, optional, tag="4")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    /// name() -> string
    #[prost(string, optional, tag="5")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
